%%keep negative probability: 0.009746775038198319
:- style_check(-discontiguous).
neg(putting_a_picture_somewhere_target(x75_0)).
neg(putting_a_picture_somewhere_target(x119_0)).
neg(putting_a_picture_somewhere_target(x137_0)).
neg(putting_a_picture_somewhere_target(x204_0)).
neg(putting_a_picture_somewhere_target(x401_0)).
neg(putting_a_picture_somewhere_target(x453_0)).
pos(putting_a_picture_somewhere_target(x494_0)).
neg(putting_a_picture_somewhere_target(x568_0)).
neg(putting_a_picture_somewhere_target(x574_0)).
neg(putting_a_picture_somewhere_target(x725_0)).
neg(putting_a_picture_somewhere_target(x740_0)).
neg(putting_a_picture_somewhere_target(x765_0)).
neg(putting_a_picture_somewhere_target(x933_0)).
neg(putting_a_picture_somewhere_target(x947_0)).
neg(putting_a_picture_somewhere_target(x1132_0)).
neg(putting_a_picture_somewhere_target(x1145_0)).
neg(putting_a_picture_somewhere_target(x1236_0)).
neg(putting_a_picture_somewhere_target(x1369_0)).
pos(putting_a_picture_somewhere_target(x1414_0)).
neg(putting_a_picture_somewhere_target(x1550_0)).
neg(putting_a_picture_somewhere_target(x1559_0)).
neg(putting_a_picture_somewhere_target(x1616_0)).
neg(putting_a_picture_somewhere_target(x1622_0)).
neg(putting_a_picture_somewhere_target(x1735_0)).
neg(putting_a_picture_somewhere_target(x1761_0)).
neg(putting_a_picture_somewhere_target(x1845_0)).
neg(putting_a_picture_somewhere_target(x2129_0)).
neg(putting_a_picture_somewhere_target(x2134_0)).
neg(putting_a_picture_somewhere_target(x2172_0)).
neg(putting_a_picture_somewhere_target(x2188_0)).
neg(putting_a_picture_somewhere_target(x2191_0)).
neg(putting_a_picture_somewhere_target(x2204_0)).
neg(putting_a_picture_somewhere_target(x2221_0)).
neg(putting_a_picture_somewhere_target(x2321_0)).
neg(putting_a_picture_somewhere_target(x2385_0)).
neg(putting_a_picture_somewhere_target(x2484_0)).
neg(putting_a_picture_somewhere_target(x2625_0)).
neg(putting_a_picture_somewhere_target(x2644_0)).
neg(putting_a_picture_somewhere_target(x2778_0)).
neg(putting_a_picture_somewhere_target(x2782_0)).
neg(putting_a_picture_somewhere_target(x2929_0)).
pos(putting_a_picture_somewhere_target(x3084_0)).
pos(putting_a_picture_somewhere_target(x3301_0)).
neg(putting_a_picture_somewhere_target(x3384_0)).
neg(putting_a_picture_somewhere_target(x3632_0)).
neg(putting_a_picture_somewhere_target(x3701_0)).
neg(putting_a_picture_somewhere_target(x3715_0)).
neg(putting_a_picture_somewhere_target(x3732_0)).
neg(putting_a_picture_somewhere_target(x3815_0)).
neg(putting_a_picture_somewhere_target(x3855_0)).
neg(putting_a_picture_somewhere_target(x4031_0)).
neg(putting_a_picture_somewhere_target(x4109_0)).
pos(putting_a_picture_somewhere_target(x4137_0)).
neg(putting_a_picture_somewhere_target(x4158_0)).
pos(putting_a_picture_somewhere_target(x4233_0)).
neg(putting_a_picture_somewhere_target(x4250_0)).
pos(putting_a_picture_somewhere_target(x4279_0)).
neg(putting_a_picture_somewhere_target(x4325_0)).
neg(putting_a_picture_somewhere_target(x4383_0)).
pos(putting_a_picture_somewhere_target(x4665_0)).
neg(putting_a_picture_somewhere_target(x4823_0)).
neg(putting_a_picture_somewhere_target(x4926_0)).
neg(putting_a_picture_somewhere_target(x4956_0)).
pos(putting_a_picture_somewhere_target(x5126_0)).
pos(putting_a_picture_somewhere_target(x5296_0)).
neg(putting_a_picture_somewhere_target(x5375_0)).
pos(putting_a_picture_somewhere_target(x5408_0)).
neg(putting_a_picture_somewhere_target(x5411_0)).
neg(putting_a_picture_somewhere_target(x5465_0)).
pos(putting_a_picture_somewhere_target(x5479_0)).
neg(putting_a_picture_somewhere_target(x5572_0)).
pos(putting_a_picture_somewhere_target(x5598_0)).
pos(putting_a_picture_somewhere_target(x5699_0)).
neg(putting_a_picture_somewhere_target(x5765_0)).
pos(putting_a_picture_somewhere_target(x5771_0)).
neg(putting_a_picture_somewhere_target(x5881_0)).
neg(putting_a_picture_somewhere_target(x5944_0)).
neg(putting_a_picture_somewhere_target(x6053_0)).
pos(putting_a_picture_somewhere_target(x6136_0)).
neg(putting_a_picture_somewhere_target(x6258_0)).
pos(putting_a_picture_somewhere_target(x6320_0)).
neg(putting_a_picture_somewhere_target(x6416_0)).
neg(putting_a_picture_somewhere_target(x6463_0)).
neg(putting_a_picture_somewhere_target(x6535_0)).
neg(putting_a_picture_somewhere_target(x6593_0)).
pos(putting_a_picture_somewhere_target(x6596_0)).
neg(putting_a_picture_somewhere_target(x6602_0)).
neg(putting_a_picture_somewhere_target(x6744_0)).
neg(putting_a_picture_somewhere_target(x6832_0)).
neg(putting_a_picture_somewhere_target(x6873_0)).
neg(putting_a_picture_somewhere_target(x7058_0)).
neg(putting_a_picture_somewhere_target(x7060_0)).
neg(putting_a_picture_somewhere_target(x7178_0)).
neg(putting_a_picture_somewhere_target(x7233_0)).
neg(putting_a_picture_somewhere_target(x7277_0)).
neg(putting_a_picture_somewhere_target(x7288_0)).
neg(putting_a_picture_somewhere_target(x7338_0)).
neg(putting_a_picture_somewhere_target(x7348_0)).
