%%keep negative probability: 0.032647927964805645
:- style_check(-discontiguous).
neg(someone_is_cooking_something_target(x11_0)).
pos(someone_is_cooking_something_target(x39_0)).
neg(someone_is_cooking_something_target(x44_0)).
neg(someone_is_cooking_something_target(x54_0)).
pos(someone_is_cooking_something_target(x60_0)).
neg(someone_is_cooking_something_target(x67_0)).
neg(someone_is_cooking_something_target(x83_0)).
neg(someone_is_cooking_something_target(x102_0)).
neg(someone_is_cooking_something_target(x116_0)).
neg(someone_is_cooking_something_target(x157_0)).
neg(someone_is_cooking_something_target(x202_0)).
neg(someone_is_cooking_something_target(x219_0)).
neg(someone_is_cooking_something_target(x224_0)).
neg(someone_is_cooking_something_target(x241_0)).
neg(someone_is_cooking_something_target(x255_0)).
neg(someone_is_cooking_something_target(x289_0)).
neg(someone_is_cooking_something_target(x320_0)).
neg(someone_is_cooking_something_target(x324_0)).
neg(someone_is_cooking_something_target(x345_0)).
neg(someone_is_cooking_something_target(x365_0)).
neg(someone_is_cooking_something_target(x367_0)).
neg(someone_is_cooking_something_target(x373_0)).
neg(someone_is_cooking_something_target(x399_0)).
neg(someone_is_cooking_something_target(x426_0)).
neg(someone_is_cooking_something_target(x427_0)).
neg(someone_is_cooking_something_target(x433_0)).
neg(someone_is_cooking_something_target(x448_0)).
neg(someone_is_cooking_something_target(x550_0)).
neg(someone_is_cooking_something_target(x582_0)).
neg(someone_is_cooking_something_target(x596_0)).
neg(someone_is_cooking_something_target(x668_0)).
neg(someone_is_cooking_something_target(x684_0)).
pos(someone_is_cooking_something_target(x713_0)).
neg(someone_is_cooking_something_target(x751_0)).
pos(someone_is_cooking_something_target(x753_0)).
neg(someone_is_cooking_something_target(x791_0)).
neg(someone_is_cooking_something_target(x810_0)).
neg(someone_is_cooking_something_target(x820_0)).
neg(someone_is_cooking_something_target(x907_0)).
neg(someone_is_cooking_something_target(x910_0)).
neg(someone_is_cooking_something_target(x936_0)).
neg(someone_is_cooking_something_target(x938_0)).
pos(someone_is_cooking_something_target(x942_0)).
neg(someone_is_cooking_something_target(x966_0)).
neg(someone_is_cooking_something_target(x979_0)).
neg(someone_is_cooking_something_target(x1038_0)).
neg(someone_is_cooking_something_target(x1065_0)).
neg(someone_is_cooking_something_target(x1093_0)).
neg(someone_is_cooking_something_target(x1153_0)).
neg(someone_is_cooking_something_target(x1157_0)).
neg(someone_is_cooking_something_target(x1162_0)).
neg(someone_is_cooking_something_target(x1172_0)).
neg(someone_is_cooking_something_target(x1234_0)).
neg(someone_is_cooking_something_target(x1257_0)).
neg(someone_is_cooking_something_target(x1291_0)).
neg(someone_is_cooking_something_target(x1343_0)).
neg(someone_is_cooking_something_target(x1348_0)).
pos(someone_is_cooking_something_target(x1370_0)).
pos(someone_is_cooking_something_target(x1377_0)).
neg(someone_is_cooking_something_target(x1381_0)).
neg(someone_is_cooking_something_target(x1468_0)).
neg(someone_is_cooking_something_target(x1471_0)).
neg(someone_is_cooking_something_target(x1509_0)).
neg(someone_is_cooking_something_target(x1543_0)).
neg(someone_is_cooking_something_target(x1566_0)).
neg(someone_is_cooking_something_target(x1586_0)).
pos(someone_is_cooking_something_target(x1633_0)).
neg(someone_is_cooking_something_target(x1659_0)).
pos(someone_is_cooking_something_target(x1670_0)).
pos(someone_is_cooking_something_target(x1692_0)).
neg(someone_is_cooking_something_target(x1772_0)).
neg(someone_is_cooking_something_target(x1816_0)).
neg(someone_is_cooking_something_target(x1832_0)).
neg(someone_is_cooking_something_target(x1866_0)).
pos(someone_is_cooking_something_target(x1877_0)).
neg(someone_is_cooking_something_target(x1894_0)).
pos(someone_is_cooking_something_target(x1965_0)).
neg(someone_is_cooking_something_target(x2004_0)).
neg(someone_is_cooking_something_target(x2011_0)).
neg(someone_is_cooking_something_target(x2059_0)).
neg(someone_is_cooking_something_target(x2070_0)).
neg(someone_is_cooking_something_target(x2157_0)).
neg(someone_is_cooking_something_target(x2164_0)).
neg(someone_is_cooking_something_target(x2198_0)).
neg(someone_is_cooking_something_target(x2236_0)).
neg(someone_is_cooking_something_target(x2252_0)).
neg(someone_is_cooking_something_target(x2288_0)).
neg(someone_is_cooking_something_target(x2290_0)).
pos(someone_is_cooking_something_target(x2293_0)).
pos(someone_is_cooking_something_target(x2297_0)).
neg(someone_is_cooking_something_target(x2302_0)).
neg(someone_is_cooking_something_target(x2325_0)).
neg(someone_is_cooking_something_target(x2379_0)).
neg(someone_is_cooking_something_target(x2385_0)).
neg(someone_is_cooking_something_target(x2413_0)).
neg(someone_is_cooking_something_target(x2496_0)).
neg(someone_is_cooking_something_target(x2522_0)).
neg(someone_is_cooking_something_target(x2529_0)).
pos(someone_is_cooking_something_target(x2549_0)).
neg(someone_is_cooking_something_target(x2570_0)).
neg(someone_is_cooking_something_target(x2586_0)).
neg(someone_is_cooking_something_target(x2590_0)).
neg(someone_is_cooking_something_target(x2618_0)).
neg(someone_is_cooking_something_target(x2625_0)).
pos(someone_is_cooking_something_target(x2656_0)).
neg(someone_is_cooking_something_target(x2721_0)).
neg(someone_is_cooking_something_target(x2723_0)).
neg(someone_is_cooking_something_target(x2729_0)).
neg(someone_is_cooking_something_target(x2755_0)).
neg(someone_is_cooking_something_target(x2757_0)).
neg(someone_is_cooking_something_target(x2768_0)).
pos(someone_is_cooking_something_target(x2793_0)).
neg(someone_is_cooking_something_target(x2866_0)).
neg(someone_is_cooking_something_target(x2874_0)).
neg(someone_is_cooking_something_target(x2902_0)).
neg(someone_is_cooking_something_target(x2930_0)).
neg(someone_is_cooking_something_target(x2974_0)).
neg(someone_is_cooking_something_target(x2976_0)).
neg(someone_is_cooking_something_target(x3024_0)).
neg(someone_is_cooking_something_target(x3053_0)).
neg(someone_is_cooking_something_target(x3081_0)).
neg(someone_is_cooking_something_target(x3189_0)).
neg(someone_is_cooking_something_target(x3269_0)).
neg(someone_is_cooking_something_target(x3280_0)).
neg(someone_is_cooking_something_target(x3294_0)).
neg(someone_is_cooking_something_target(x3310_0)).
neg(someone_is_cooking_something_target(x3334_0)).
pos(someone_is_cooking_something_target(x3341_0)).
neg(someone_is_cooking_something_target(x3350_0)).
pos(someone_is_cooking_something_target(x3365_0)).
neg(someone_is_cooking_something_target(x3377_0)).
pos(someone_is_cooking_something_target(x3436_0)).
pos(someone_is_cooking_something_target(x3455_0)).
neg(someone_is_cooking_something_target(x3480_0)).
neg(someone_is_cooking_something_target(x3537_0)).
pos(someone_is_cooking_something_target(x3561_0)).
neg(someone_is_cooking_something_target(x3596_0)).
neg(someone_is_cooking_something_target(x3609_0)).
neg(someone_is_cooking_something_target(x3618_0)).
neg(someone_is_cooking_something_target(x3637_0)).
neg(someone_is_cooking_something_target(x3655_0)).
neg(someone_is_cooking_something_target(x3687_0)).
pos(someone_is_cooking_something_target(x3693_0)).
neg(someone_is_cooking_something_target(x3700_0)).
neg(someone_is_cooking_something_target(x3718_0)).
neg(someone_is_cooking_something_target(x3721_0)).
neg(someone_is_cooking_something_target(x3736_0)).
neg(someone_is_cooking_something_target(x3779_0)).
neg(someone_is_cooking_something_target(x3810_0)).
neg(someone_is_cooking_something_target(x3833_0)).
neg(someone_is_cooking_something_target(x3834_0)).
pos(someone_is_cooking_something_target(x3840_0)).
pos(someone_is_cooking_something_target(x3875_0)).
pos(someone_is_cooking_something_target(x3887_0)).
neg(someone_is_cooking_something_target(x3912_0)).
pos(someone_is_cooking_something_target(x3935_0)).
pos(someone_is_cooking_something_target(x3952_0)).
pos(someone_is_cooking_something_target(x3963_0)).
neg(someone_is_cooking_something_target(x4009_0)).
neg(someone_is_cooking_something_target(x4033_0)).
pos(someone_is_cooking_something_target(x4035_0)).
neg(someone_is_cooking_something_target(x4048_0)).
neg(someone_is_cooking_something_target(x4053_0)).
neg(someone_is_cooking_something_target(x4083_0)).
pos(someone_is_cooking_something_target(x4110_0)).
neg(someone_is_cooking_something_target(x4119_0)).
neg(someone_is_cooking_something_target(x4183_0)).
neg(someone_is_cooking_something_target(x4185_0)).
neg(someone_is_cooking_something_target(x4209_0)).
neg(someone_is_cooking_something_target(x4217_0)).
neg(someone_is_cooking_something_target(x4227_0)).
pos(someone_is_cooking_something_target(x4276_0)).
pos(someone_is_cooking_something_target(x4277_0)).
neg(someone_is_cooking_something_target(x4286_0)).
neg(someone_is_cooking_something_target(x4305_0)).
pos(someone_is_cooking_something_target(x4332_0)).
neg(someone_is_cooking_something_target(x4362_0)).
neg(someone_is_cooking_something_target(x4404_0)).
neg(someone_is_cooking_something_target(x4420_0)).
neg(someone_is_cooking_something_target(x4440_0)).
neg(someone_is_cooking_something_target(x4509_0)).
neg(someone_is_cooking_something_target(x4529_0)).
neg(someone_is_cooking_something_target(x4536_0)).
neg(someone_is_cooking_something_target(x4560_0)).
neg(someone_is_cooking_something_target(x4601_0)).
neg(someone_is_cooking_something_target(x4605_0)).
neg(someone_is_cooking_something_target(x4666_0)).
neg(someone_is_cooking_something_target(x4724_0)).
neg(someone_is_cooking_something_target(x4744_0)).
neg(someone_is_cooking_something_target(x4789_0)).
neg(someone_is_cooking_something_target(x4793_0)).
neg(someone_is_cooking_something_target(x4816_0)).
neg(someone_is_cooking_something_target(x4850_0)).
neg(someone_is_cooking_something_target(x4864_0)).
neg(someone_is_cooking_something_target(x4872_0)).
neg(someone_is_cooking_something_target(x4874_0)).
neg(someone_is_cooking_something_target(x4897_0)).
neg(someone_is_cooking_something_target(x4917_0)).
pos(someone_is_cooking_something_target(x4930_0)).
pos(someone_is_cooking_something_target(x4931_0)).
neg(someone_is_cooking_something_target(x4957_0)).
neg(someone_is_cooking_something_target(x4971_0)).
pos(someone_is_cooking_something_target(x5050_0)).
neg(someone_is_cooking_something_target(x5068_0)).
neg(someone_is_cooking_something_target(x5100_0)).
neg(someone_is_cooking_something_target(x5164_0)).
neg(someone_is_cooking_something_target(x5167_0)).
neg(someone_is_cooking_something_target(x5255_0)).
pos(someone_is_cooking_something_target(x5281_0)).
neg(someone_is_cooking_something_target(x5289_0)).
neg(someone_is_cooking_something_target(x5332_0)).
neg(someone_is_cooking_something_target(x5338_0)).
neg(someone_is_cooking_something_target(x5353_0)).
neg(someone_is_cooking_something_target(x5379_0)).
neg(someone_is_cooking_something_target(x5409_0)).
neg(someone_is_cooking_something_target(x5515_0)).
pos(someone_is_cooking_something_target(x5574_0)).
neg(someone_is_cooking_something_target(x5579_0)).
pos(someone_is_cooking_something_target(x5584_0)).
neg(someone_is_cooking_something_target(x5608_0)).
neg(someone_is_cooking_something_target(x5670_0)).
neg(someone_is_cooking_something_target(x5687_0)).
neg(someone_is_cooking_something_target(x5692_0)).
neg(someone_is_cooking_something_target(x5717_0)).
neg(someone_is_cooking_something_target(x5759_0)).
neg(someone_is_cooking_something_target(x5765_0)).
neg(someone_is_cooking_something_target(x5786_0)).
neg(someone_is_cooking_something_target(x5789_0)).
neg(someone_is_cooking_something_target(x5798_0)).
neg(someone_is_cooking_something_target(x5812_0)).
neg(someone_is_cooking_something_target(x5842_0)).
neg(someone_is_cooking_something_target(x5862_0)).
neg(someone_is_cooking_something_target(x5883_0)).
neg(someone_is_cooking_something_target(x5948_0)).
neg(someone_is_cooking_something_target(x5980_0)).
neg(someone_is_cooking_something_target(x6003_0)).
pos(someone_is_cooking_something_target(x6018_0)).
neg(someone_is_cooking_something_target(x6027_0)).
neg(someone_is_cooking_something_target(x6061_0)).
neg(someone_is_cooking_something_target(x6097_0)).
neg(someone_is_cooking_something_target(x6102_0)).
pos(someone_is_cooking_something_target(x6111_0)).
pos(someone_is_cooking_something_target(x6131_0)).
pos(someone_is_cooking_something_target(x6132_0)).
neg(someone_is_cooking_something_target(x6151_0)).
pos(someone_is_cooking_something_target(x6152_0)).
neg(someone_is_cooking_something_target(x6154_0)).
neg(someone_is_cooking_something_target(x6163_0)).
pos(someone_is_cooking_something_target(x6174_0)).
neg(someone_is_cooking_something_target(x6180_0)).
neg(someone_is_cooking_something_target(x6213_0)).
neg(someone_is_cooking_something_target(x6223_0)).
neg(someone_is_cooking_something_target(x6237_0)).
pos(someone_is_cooking_something_target(x6246_0)).
pos(someone_is_cooking_something_target(x6251_0)).
neg(someone_is_cooking_something_target(x6259_0)).
neg(someone_is_cooking_something_target(x6266_0)).
neg(someone_is_cooking_something_target(x6360_0)).
neg(someone_is_cooking_something_target(x6391_0)).
pos(someone_is_cooking_something_target(x6465_0)).
pos(someone_is_cooking_something_target(x6471_0)).
pos(someone_is_cooking_something_target(x6501_0)).
pos(someone_is_cooking_something_target(x6502_0)).
neg(someone_is_cooking_something_target(x6514_0)).
neg(someone_is_cooking_something_target(x6534_0)).
neg(someone_is_cooking_something_target(x6592_0)).
neg(someone_is_cooking_something_target(x6593_0)).
neg(someone_is_cooking_something_target(x6605_0)).
neg(someone_is_cooking_something_target(x6614_0)).
neg(someone_is_cooking_something_target(x6640_0)).
neg(someone_is_cooking_something_target(x6704_0)).
pos(someone_is_cooking_something_target(x6713_0)).
neg(someone_is_cooking_something_target(x6758_0)).
pos(someone_is_cooking_something_target(x6837_0)).
neg(someone_is_cooking_something_target(x6868_0)).
pos(someone_is_cooking_something_target(x6873_0)).
neg(someone_is_cooking_something_target(x6902_0)).
pos(someone_is_cooking_something_target(x6924_0)).
pos(someone_is_cooking_something_target(x6925_0)).
neg(someone_is_cooking_something_target(x6939_0)).
pos(someone_is_cooking_something_target(x6952_0)).
pos(someone_is_cooking_something_target(x6955_0)).
neg(someone_is_cooking_something_target(x6968_0)).
neg(someone_is_cooking_something_target(x6974_0)).
neg(someone_is_cooking_something_target(x6983_0)).
neg(someone_is_cooking_something_target(x6984_0)).
neg(someone_is_cooking_something_target(x7003_0)).
neg(someone_is_cooking_something_target(x7035_0)).
neg(someone_is_cooking_something_target(x7056_0)).
neg(someone_is_cooking_something_target(x7148_0)).
pos(someone_is_cooking_something_target(x7165_0)).
neg(someone_is_cooking_something_target(x7176_0)).
pos(someone_is_cooking_something_target(x7189_0)).
neg(someone_is_cooking_something_target(x7317_0)).
neg(someone_is_cooking_something_target(x7334_0)).
