%%keep negative probability: 0.014584479614624501
:- style_check(-discontiguous).
neg(taking_a_pillow_from_somewhere_target(x13_0)).
neg(taking_a_pillow_from_somewhere_target(x23_0)).
neg(taking_a_pillow_from_somewhere_target(x73_0)).
neg(taking_a_pillow_from_somewhere_target(x107_0)).
neg(taking_a_pillow_from_somewhere_target(x110_0)).
neg(taking_a_pillow_from_somewhere_target(x134_0)).
neg(taking_a_pillow_from_somewhere_target(x193_0)).
neg(taking_a_pillow_from_somewhere_target(x283_0)).
neg(taking_a_pillow_from_somewhere_target(x384_0)).
neg(taking_a_pillow_from_somewhere_target(x420_0)).
neg(taking_a_pillow_from_somewhere_target(x445_0)).
pos(taking_a_pillow_from_somewhere_target(x488_0)).
neg(taking_a_pillow_from_somewhere_target(x614_0)).
neg(taking_a_pillow_from_somewhere_target(x652_0)).
neg(taking_a_pillow_from_somewhere_target(x685_0)).
neg(taking_a_pillow_from_somewhere_target(x765_0)).
neg(taking_a_pillow_from_somewhere_target(x831_0)).
pos(taking_a_pillow_from_somewhere_target(x924_0)).
neg(taking_a_pillow_from_somewhere_target(x929_0)).
neg(taking_a_pillow_from_somewhere_target(x939_0)).
neg(taking_a_pillow_from_somewhere_target(x942_0)).
pos(taking_a_pillow_from_somewhere_target(x948_0)).
neg(taking_a_pillow_from_somewhere_target(x972_0)).
neg(taking_a_pillow_from_somewhere_target(x1062_0)).
pos(taking_a_pillow_from_somewhere_target(x1274_0)).
neg(taking_a_pillow_from_somewhere_target(x1295_0)).
pos(taking_a_pillow_from_somewhere_target(x1308_0)).
pos(taking_a_pillow_from_somewhere_target(x1386_0)).
neg(taking_a_pillow_from_somewhere_target(x1449_0)).
pos(taking_a_pillow_from_somewhere_target(x1482_0)).
neg(taking_a_pillow_from_somewhere_target(x1498_0)).
neg(taking_a_pillow_from_somewhere_target(x1527_0)).
neg(taking_a_pillow_from_somewhere_target(x1530_0)).
neg(taking_a_pillow_from_somewhere_target(x1671_0)).
neg(taking_a_pillow_from_somewhere_target(x1697_0)).
neg(taking_a_pillow_from_somewhere_target(x1703_0)).
neg(taking_a_pillow_from_somewhere_target(x1781_0)).
pos(taking_a_pillow_from_somewhere_target(x1787_0)).
neg(taking_a_pillow_from_somewhere_target(x1793_0)).
neg(taking_a_pillow_from_somewhere_target(x1869_0)).
neg(taking_a_pillow_from_somewhere_target(x2038_0)).
neg(taking_a_pillow_from_somewhere_target(x2070_0)).
neg(taking_a_pillow_from_somewhere_target(x2166_0)).
neg(taking_a_pillow_from_somewhere_target(x2167_0)).
pos(taking_a_pillow_from_somewhere_target(x2220_0)).
neg(taking_a_pillow_from_somewhere_target(x2268_0)).
neg(taking_a_pillow_from_somewhere_target(x2336_0)).
pos(taking_a_pillow_from_somewhere_target(x2374_0)).
neg(taking_a_pillow_from_somewhere_target(x2412_0)).
neg(taking_a_pillow_from_somewhere_target(x2417_0)).
neg(taking_a_pillow_from_somewhere_target(x2459_0)).
pos(taking_a_pillow_from_somewhere_target(x2480_0)).
neg(taking_a_pillow_from_somewhere_target(x2528_0)).
neg(taking_a_pillow_from_somewhere_target(x2569_0)).
neg(taking_a_pillow_from_somewhere_target(x2627_0)).
neg(taking_a_pillow_from_somewhere_target(x2652_0)).
neg(taking_a_pillow_from_somewhere_target(x2665_0)).
neg(taking_a_pillow_from_somewhere_target(x2738_0)).
neg(taking_a_pillow_from_somewhere_target(x2739_0)).
neg(taking_a_pillow_from_somewhere_target(x2764_0)).
neg(taking_a_pillow_from_somewhere_target(x2788_0)).
neg(taking_a_pillow_from_somewhere_target(x2853_0)).
neg(taking_a_pillow_from_somewhere_target(x2898_0)).
neg(taking_a_pillow_from_somewhere_target(x2927_0)).
neg(taking_a_pillow_from_somewhere_target(x2977_0)).
neg(taking_a_pillow_from_somewhere_target(x3095_0)).
neg(taking_a_pillow_from_somewhere_target(x3096_0)).
pos(taking_a_pillow_from_somewhere_target(x3123_0)).
neg(taking_a_pillow_from_somewhere_target(x3289_0)).
neg(taking_a_pillow_from_somewhere_target(x3315_0)).
neg(taking_a_pillow_from_somewhere_target(x3333_0)).
neg(taking_a_pillow_from_somewhere_target(x3420_0)).
neg(taking_a_pillow_from_somewhere_target(x3433_0)).
neg(taking_a_pillow_from_somewhere_target(x3443_0)).
neg(taking_a_pillow_from_somewhere_target(x3528_0)).
neg(taking_a_pillow_from_somewhere_target(x3637_0)).
neg(taking_a_pillow_from_somewhere_target(x3658_0)).
neg(taking_a_pillow_from_somewhere_target(x3676_0)).
neg(taking_a_pillow_from_somewhere_target(x3679_0)).
pos(taking_a_pillow_from_somewhere_target(x3699_0)).
neg(taking_a_pillow_from_somewhere_target(x3761_0)).
neg(taking_a_pillow_from_somewhere_target(x3773_0)).
neg(taking_a_pillow_from_somewhere_target(x3779_0)).
neg(taking_a_pillow_from_somewhere_target(x3858_0)).
pos(taking_a_pillow_from_somewhere_target(x3880_0)).
neg(taking_a_pillow_from_somewhere_target(x4013_0)).
neg(taking_a_pillow_from_somewhere_target(x4017_0)).
neg(taking_a_pillow_from_somewhere_target(x4064_0)).
neg(taking_a_pillow_from_somewhere_target(x4152_0)).
neg(taking_a_pillow_from_somewhere_target(x4189_0)).
neg(taking_a_pillow_from_somewhere_target(x4213_0)).
neg(taking_a_pillow_from_somewhere_target(x4252_0)).
pos(taking_a_pillow_from_somewhere_target(x4287_0)).
neg(taking_a_pillow_from_somewhere_target(x4303_0)).
pos(taking_a_pillow_from_somewhere_target(x4348_0)).
neg(taking_a_pillow_from_somewhere_target(x4378_0)).
neg(taking_a_pillow_from_somewhere_target(x4438_0)).
pos(taking_a_pillow_from_somewhere_target(x4520_0)).
neg(taking_a_pillow_from_somewhere_target(x4664_0)).
pos(taking_a_pillow_from_somewhere_target(x4702_0)).
neg(taking_a_pillow_from_somewhere_target(x4707_0)).
pos(taking_a_pillow_from_somewhere_target(x4716_0)).
pos(taking_a_pillow_from_somewhere_target(x4770_0)).
neg(taking_a_pillow_from_somewhere_target(x4810_0)).
neg(taking_a_pillow_from_somewhere_target(x4891_0)).
pos(taking_a_pillow_from_somewhere_target(x4922_0)).
neg(taking_a_pillow_from_somewhere_target(x4981_0)).
neg(taking_a_pillow_from_somewhere_target(x5069_0)).
pos(taking_a_pillow_from_somewhere_target(x5089_0)).
neg(taking_a_pillow_from_somewhere_target(x5541_0)).
neg(taking_a_pillow_from_somewhere_target(x5588_0)).
neg(taking_a_pillow_from_somewhere_target(x5648_0)).
pos(taking_a_pillow_from_somewhere_target(x5716_0)).
neg(taking_a_pillow_from_somewhere_target(x5757_0)).
pos(taking_a_pillow_from_somewhere_target(x5822_0)).
neg(taking_a_pillow_from_somewhere_target(x5824_0)).
neg(taking_a_pillow_from_somewhere_target(x5998_0)).
neg(taking_a_pillow_from_somewhere_target(x6129_0)).
neg(taking_a_pillow_from_somewhere_target(x6236_0)).
neg(taking_a_pillow_from_somewhere_target(x6272_0)).
pos(taking_a_pillow_from_somewhere_target(x6302_0)).
pos(taking_a_pillow_from_somewhere_target(x6329_0)).
neg(taking_a_pillow_from_somewhere_target(x6511_0)).
neg(taking_a_pillow_from_somewhere_target(x6517_0)).
neg(taking_a_pillow_from_somewhere_target(x6525_0)).
neg(taking_a_pillow_from_somewhere_target(x6589_0)).
neg(taking_a_pillow_from_somewhere_target(x6730_0)).
neg(taking_a_pillow_from_somewhere_target(x6742_0)).
neg(taking_a_pillow_from_somewhere_target(x6747_0)).
neg(taking_a_pillow_from_somewhere_target(x6763_0)).
neg(taking_a_pillow_from_somewhere_target(x6779_0)).
neg(taking_a_pillow_from_somewhere_target(x6835_0)).
neg(taking_a_pillow_from_somewhere_target(x6838_0)).
pos(taking_a_pillow_from_somewhere_target(x6891_0)).
neg(taking_a_pillow_from_somewhere_target(x7038_0)).
neg(taking_a_pillow_from_somewhere_target(x7161_0)).
neg(taking_a_pillow_from_somewhere_target(x7269_0)).
neg(taking_a_pillow_from_somewhere_target(x7274_0)).
neg(taking_a_pillow_from_somewhere_target(x7327_0)).
