%%keep negative probability: 0.018864817196338368
:- style_check(-discontiguous).
neg(taking_a_book_from_somewhere_target(x13_0)).
pos(taking_a_book_from_somewhere_target(x65_0)).
neg(taking_a_book_from_somewhere_target(x102_0)).
neg(taking_a_book_from_somewhere_target(x117_0)).
neg(taking_a_book_from_somewhere_target(x151_0)).
pos(taking_a_book_from_somewhere_target(x169_0)).
neg(taking_a_book_from_somewhere_target(x217_0)).
neg(taking_a_book_from_somewhere_target(x226_0)).
neg(taking_a_book_from_somewhere_target(x244_0)).
neg(taking_a_book_from_somewhere_target(x262_0)).
neg(taking_a_book_from_somewhere_target(x278_0)).
neg(taking_a_book_from_somewhere_target(x285_0)).
neg(taking_a_book_from_somewhere_target(x344_0)).
pos(taking_a_book_from_somewhere_target(x355_0)).
pos(taking_a_book_from_somewhere_target(x424_0)).
neg(taking_a_book_from_somewhere_target(x452_0)).
pos(taking_a_book_from_somewhere_target(x552_0)).
neg(taking_a_book_from_somewhere_target(x557_0)).
pos(taking_a_book_from_somewhere_target(x569_0)).
neg(taking_a_book_from_somewhere_target(x600_0)).
neg(taking_a_book_from_somewhere_target(x622_0)).
neg(taking_a_book_from_somewhere_target(x641_0)).
neg(taking_a_book_from_somewhere_target(x732_0)).
neg(taking_a_book_from_somewhere_target(x784_0)).
neg(taking_a_book_from_somewhere_target(x834_0)).
pos(taking_a_book_from_somewhere_target(x881_0)).
neg(taking_a_book_from_somewhere_target(x960_0)).
neg(taking_a_book_from_somewhere_target(x994_0)).
pos(taking_a_book_from_somewhere_target(x1011_0)).
neg(taking_a_book_from_somewhere_target(x1062_0)).
neg(taking_a_book_from_somewhere_target(x1067_0)).
neg(taking_a_book_from_somewhere_target(x1072_0)).
neg(taking_a_book_from_somewhere_target(x1171_0)).
neg(taking_a_book_from_somewhere_target(x1210_0)).
neg(taking_a_book_from_somewhere_target(x1253_0)).
pos(taking_a_book_from_somewhere_target(x1262_0)).
neg(taking_a_book_from_somewhere_target(x1279_0)).
neg(taking_a_book_from_somewhere_target(x1283_0)).
neg(taking_a_book_from_somewhere_target(x1291_0)).
neg(taking_a_book_from_somewhere_target(x1370_0)).
neg(taking_a_book_from_somewhere_target(x1453_0)).
neg(taking_a_book_from_somewhere_target(x1470_0)).
pos(taking_a_book_from_somewhere_target(x1475_0)).
pos(taking_a_book_from_somewhere_target(x1485_0)).
neg(taking_a_book_from_somewhere_target(x1549_0)).
neg(taking_a_book_from_somewhere_target(x1616_0)).
neg(taking_a_book_from_somewhere_target(x1684_0)).
neg(taking_a_book_from_somewhere_target(x1709_0)).
neg(taking_a_book_from_somewhere_target(x1712_0)).
neg(taking_a_book_from_somewhere_target(x1750_0)).
neg(taking_a_book_from_somewhere_target(x1843_0)).
neg(taking_a_book_from_somewhere_target(x1924_0)).
neg(taking_a_book_from_somewhere_target(x1933_0)).
neg(taking_a_book_from_somewhere_target(x1971_0)).
neg(taking_a_book_from_somewhere_target(x2041_0)).
neg(taking_a_book_from_somewhere_target(x2149_0)).
pos(taking_a_book_from_somewhere_target(x2182_0)).
neg(taking_a_book_from_somewhere_target(x2226_0)).
neg(taking_a_book_from_somewhere_target(x2264_0)).
neg(taking_a_book_from_somewhere_target(x2271_0)).
neg(taking_a_book_from_somewhere_target(x2308_0)).
neg(taking_a_book_from_somewhere_target(x2318_0)).
neg(taking_a_book_from_somewhere_target(x2369_0)).
neg(taking_a_book_from_somewhere_target(x2420_0)).
neg(taking_a_book_from_somewhere_target(x2431_0)).
neg(taking_a_book_from_somewhere_target(x2479_0)).
neg(taking_a_book_from_somewhere_target(x2484_0)).
neg(taking_a_book_from_somewhere_target(x2524_0)).
neg(taking_a_book_from_somewhere_target(x2576_0)).
neg(taking_a_book_from_somewhere_target(x2611_0)).
pos(taking_a_book_from_somewhere_target(x2655_0)).
neg(taking_a_book_from_somewhere_target(x2659_0)).
neg(taking_a_book_from_somewhere_target(x2680_0)).
neg(taking_a_book_from_somewhere_target(x2864_0)).
neg(taking_a_book_from_somewhere_target(x2921_0)).
neg(taking_a_book_from_somewhere_target(x2960_0)).
neg(taking_a_book_from_somewhere_target(x2973_0)).
neg(taking_a_book_from_somewhere_target(x2981_0)).
neg(taking_a_book_from_somewhere_target(x2984_0)).
neg(taking_a_book_from_somewhere_target(x2998_0)).
pos(taking_a_book_from_somewhere_target(x3143_0)).
pos(taking_a_book_from_somewhere_target(x3174_0)).
neg(taking_a_book_from_somewhere_target(x3202_0)).
neg(taking_a_book_from_somewhere_target(x3242_0)).
neg(taking_a_book_from_somewhere_target(x3386_0)).
neg(taking_a_book_from_somewhere_target(x3587_0)).
neg(taking_a_book_from_somewhere_target(x3597_0)).
neg(taking_a_book_from_somewhere_target(x3650_0)).
neg(taking_a_book_from_somewhere_target(x3677_0)).
pos(taking_a_book_from_somewhere_target(x3678_0)).
neg(taking_a_book_from_somewhere_target(x3818_0)).
neg(taking_a_book_from_somewhere_target(x3820_0)).
neg(taking_a_book_from_somewhere_target(x3888_0)).
neg(taking_a_book_from_somewhere_target(x3896_0)).
pos(taking_a_book_from_somewhere_target(x3904_0)).
neg(taking_a_book_from_somewhere_target(x3957_0)).
neg(taking_a_book_from_somewhere_target(x3970_0)).
neg(taking_a_book_from_somewhere_target(x3990_0)).
neg(taking_a_book_from_somewhere_target(x3993_0)).
neg(taking_a_book_from_somewhere_target(x4000_0)).
neg(taking_a_book_from_somewhere_target(x4062_0)).
neg(taking_a_book_from_somewhere_target(x4211_0)).
pos(taking_a_book_from_somewhere_target(x4229_0)).
neg(taking_a_book_from_somewhere_target(x4273_0)).
neg(taking_a_book_from_somewhere_target(x4293_0)).
pos(taking_a_book_from_somewhere_target(x4325_0)).
neg(taking_a_book_from_somewhere_target(x4346_0)).
neg(taking_a_book_from_somewhere_target(x4457_0)).
neg(taking_a_book_from_somewhere_target(x4483_0)).
neg(taking_a_book_from_somewhere_target(x4521_0)).
neg(taking_a_book_from_somewhere_target(x4588_0)).
neg(taking_a_book_from_somewhere_target(x4703_0)).
neg(taking_a_book_from_somewhere_target(x4734_0)).
neg(taking_a_book_from_somewhere_target(x4744_0)).
pos(taking_a_book_from_somewhere_target(x4862_0)).
pos(taking_a_book_from_somewhere_target(x4914_0)).
neg(taking_a_book_from_somewhere_target(x4927_0)).
neg(taking_a_book_from_somewhere_target(x4957_0)).
pos(taking_a_book_from_somewhere_target(x5012_0)).
neg(taking_a_book_from_somewhere_target(x5032_0)).
neg(taking_a_book_from_somewhere_target(x5063_0)).
neg(taking_a_book_from_somewhere_target(x5066_0)).
neg(taking_a_book_from_somewhere_target(x5074_0)).
neg(taking_a_book_from_somewhere_target(x5144_0)).
neg(taking_a_book_from_somewhere_target(x5199_0)).
neg(taking_a_book_from_somewhere_target(x5207_0)).
neg(taking_a_book_from_somewhere_target(x5218_0)).
neg(taking_a_book_from_somewhere_target(x5259_0)).
neg(taking_a_book_from_somewhere_target(x5314_0)).
neg(taking_a_book_from_somewhere_target(x5325_0)).
neg(taking_a_book_from_somewhere_target(x5328_0)).
pos(taking_a_book_from_somewhere_target(x5347_0)).
neg(taking_a_book_from_somewhere_target(x5359_0)).
neg(taking_a_book_from_somewhere_target(x5377_0)).
pos(taking_a_book_from_somewhere_target(x5426_0)).
pos(taking_a_book_from_somewhere_target(x5440_0)).
pos(taking_a_book_from_somewhere_target(x5537_0)).
neg(taking_a_book_from_somewhere_target(x5637_0)).
neg(taking_a_book_from_somewhere_target(x5703_0)).
pos(taking_a_book_from_somewhere_target(x5713_0)).
neg(taking_a_book_from_somewhere_target(x5811_0)).
neg(taking_a_book_from_somewhere_target(x5868_0)).
neg(taking_a_book_from_somewhere_target(x5936_0)).
neg(taking_a_book_from_somewhere_target(x5993_0)).
neg(taking_a_book_from_somewhere_target(x5995_0)).
neg(taking_a_book_from_somewhere_target(x6028_0)).
neg(taking_a_book_from_somewhere_target(x6061_0)).
neg(taking_a_book_from_somewhere_target(x6074_0)).
pos(taking_a_book_from_somewhere_target(x6157_0)).
neg(taking_a_book_from_somewhere_target(x6160_0)).
neg(taking_a_book_from_somewhere_target(x6264_0)).
neg(taking_a_book_from_somewhere_target(x6273_0)).
neg(taking_a_book_from_somewhere_target(x6282_0)).
neg(taking_a_book_from_somewhere_target(x6306_0)).
neg(taking_a_book_from_somewhere_target(x6311_0)).
pos(taking_a_book_from_somewhere_target(x6342_0)).
neg(taking_a_book_from_somewhere_target(x6351_0)).
pos(taking_a_book_from_somewhere_target(x6444_0)).
neg(taking_a_book_from_somewhere_target(x6456_0)).
neg(taking_a_book_from_somewhere_target(x6504_0)).
neg(taking_a_book_from_somewhere_target(x6589_0)).
neg(taking_a_book_from_somewhere_target(x6625_0)).
pos(taking_a_book_from_somewhere_target(x6668_0)).
pos(taking_a_book_from_somewhere_target(x6724_0)).
pos(taking_a_book_from_somewhere_target(x6726_0)).
neg(taking_a_book_from_somewhere_target(x6790_0)).
neg(taking_a_book_from_somewhere_target(x6934_0)).
neg(taking_a_book_from_somewhere_target(x6981_0)).
neg(taking_a_book_from_somewhere_target(x6991_0)).
neg(taking_a_book_from_somewhere_target(x7028_0)).
neg(taking_a_book_from_somewhere_target(x7041_0)).
neg(taking_a_book_from_somewhere_target(x7068_0)).
neg(taking_a_book_from_somewhere_target(x7076_0)).
neg(taking_a_book_from_somewhere_target(x7111_0)).
neg(taking_a_book_from_somewhere_target(x7224_0)).
neg(taking_a_book_from_somewhere_target(x7285_0)).
neg(taking_a_book_from_somewhere_target(x7301_0)).
pos(taking_a_book_from_somewhere_target(x7339_0)).
