%%keep negative probability: 0.03684980356248424
:- style_check(-discontiguous).
pos(throwing_something_on_the_floor_target(x1_0)).
neg(throwing_something_on_the_floor_target(x36_0)).
neg(throwing_something_on_the_floor_target(x64_0)).
neg(throwing_something_on_the_floor_target(x75_0)).
neg(throwing_something_on_the_floor_target(x84_0)).
neg(throwing_something_on_the_floor_target(x102_0)).
neg(throwing_something_on_the_floor_target(x156_0)).
neg(throwing_something_on_the_floor_target(x158_0)).
neg(throwing_something_on_the_floor_target(x170_0)).
neg(throwing_something_on_the_floor_target(x179_0)).
neg(throwing_something_on_the_floor_target(x182_0)).
neg(throwing_something_on_the_floor_target(x190_0)).
neg(throwing_something_on_the_floor_target(x238_0)).
neg(throwing_something_on_the_floor_target(x270_0)).
neg(throwing_something_on_the_floor_target(x313_0)).
pos(throwing_something_on_the_floor_target(x314_0)).
neg(throwing_something_on_the_floor_target(x365_0)).
neg(throwing_something_on_the_floor_target(x371_0)).
neg(throwing_something_on_the_floor_target(x436_0)).
pos(throwing_something_on_the_floor_target(x453_0)).
neg(throwing_something_on_the_floor_target(x455_0)).
neg(throwing_something_on_the_floor_target(x462_0)).
pos(throwing_something_on_the_floor_target(x465_0)).
pos(throwing_something_on_the_floor_target(x516_0)).
neg(throwing_something_on_the_floor_target(x520_0)).
neg(throwing_something_on_the_floor_target(x572_0)).
neg(throwing_something_on_the_floor_target(x588_0)).
pos(throwing_something_on_the_floor_target(x598_0)).
neg(throwing_something_on_the_floor_target(x603_0)).
neg(throwing_something_on_the_floor_target(x620_0)).
neg(throwing_something_on_the_floor_target(x649_0)).
neg(throwing_something_on_the_floor_target(x662_0)).
pos(throwing_something_on_the_floor_target(x700_0)).
neg(throwing_something_on_the_floor_target(x733_0)).
neg(throwing_something_on_the_floor_target(x747_0)).
neg(throwing_something_on_the_floor_target(x749_0)).
neg(throwing_something_on_the_floor_target(x761_0)).
pos(throwing_something_on_the_floor_target(x766_0)).
neg(throwing_something_on_the_floor_target(x767_0)).
neg(throwing_something_on_the_floor_target(x778_0)).
neg(throwing_something_on_the_floor_target(x810_0)).
neg(throwing_something_on_the_floor_target(x839_0)).
neg(throwing_something_on_the_floor_target(x912_0)).
neg(throwing_something_on_the_floor_target(x945_0)).
neg(throwing_something_on_the_floor_target(x954_0)).
neg(throwing_something_on_the_floor_target(x967_0)).
neg(throwing_something_on_the_floor_target(x980_0)).
neg(throwing_something_on_the_floor_target(x1019_0)).
neg(throwing_something_on_the_floor_target(x1032_0)).
pos(throwing_something_on_the_floor_target(x1043_0)).
neg(throwing_something_on_the_floor_target(x1077_0)).
neg(throwing_something_on_the_floor_target(x1090_0)).
neg(throwing_something_on_the_floor_target(x1091_0)).
neg(throwing_something_on_the_floor_target(x1143_0)).
neg(throwing_something_on_the_floor_target(x1144_0)).
pos(throwing_something_on_the_floor_target(x1151_0)).
neg(throwing_something_on_the_floor_target(x1163_0)).
neg(throwing_something_on_the_floor_target(x1168_0)).
neg(throwing_something_on_the_floor_target(x1193_0)).
neg(throwing_something_on_the_floor_target(x1205_0)).
neg(throwing_something_on_the_floor_target(x1209_0)).
neg(throwing_something_on_the_floor_target(x1217_0)).
pos(throwing_something_on_the_floor_target(x1235_0)).
neg(throwing_something_on_the_floor_target(x1270_0)).
pos(throwing_something_on_the_floor_target(x1275_0)).
neg(throwing_something_on_the_floor_target(x1277_0)).
pos(throwing_something_on_the_floor_target(x1309_0)).
pos(throwing_something_on_the_floor_target(x1323_0)).
neg(throwing_something_on_the_floor_target(x1325_0)).
neg(throwing_something_on_the_floor_target(x1335_0)).
neg(throwing_something_on_the_floor_target(x1337_0)).
pos(throwing_something_on_the_floor_target(x1339_0)).
neg(throwing_something_on_the_floor_target(x1341_0)).
neg(throwing_something_on_the_floor_target(x1359_0)).
neg(throwing_something_on_the_floor_target(x1360_0)).
neg(throwing_something_on_the_floor_target(x1374_0)).
pos(throwing_something_on_the_floor_target(x1388_0)).
pos(throwing_something_on_the_floor_target(x1405_0)).
pos(throwing_something_on_the_floor_target(x1420_0)).
neg(throwing_something_on_the_floor_target(x1435_0)).
neg(throwing_something_on_the_floor_target(x1450_0)).
neg(throwing_something_on_the_floor_target(x1454_0)).
pos(throwing_something_on_the_floor_target(x1526_0)).
neg(throwing_something_on_the_floor_target(x1531_0)).
neg(throwing_something_on_the_floor_target(x1532_0)).
neg(throwing_something_on_the_floor_target(x1536_0)).
neg(throwing_something_on_the_floor_target(x1539_0)).
neg(throwing_something_on_the_floor_target(x1554_0)).
pos(throwing_something_on_the_floor_target(x1558_0)).
pos(throwing_something_on_the_floor_target(x1559_0)).
neg(throwing_something_on_the_floor_target(x1574_0)).
neg(throwing_something_on_the_floor_target(x1582_0)).
neg(throwing_something_on_the_floor_target(x1625_0)).
pos(throwing_something_on_the_floor_target(x1650_0)).
neg(throwing_something_on_the_floor_target(x1653_0)).
neg(throwing_something_on_the_floor_target(x1670_0)).
neg(throwing_something_on_the_floor_target(x1671_0)).
pos(throwing_something_on_the_floor_target(x1674_0)).
neg(throwing_something_on_the_floor_target(x1702_0)).
neg(throwing_something_on_the_floor_target(x1739_0)).
neg(throwing_something_on_the_floor_target(x1770_0)).
neg(throwing_something_on_the_floor_target(x1778_0)).
neg(throwing_something_on_the_floor_target(x1800_0)).
neg(throwing_something_on_the_floor_target(x1810_0)).
neg(throwing_something_on_the_floor_target(x1820_0)).
neg(throwing_something_on_the_floor_target(x1825_0)).
neg(throwing_something_on_the_floor_target(x1869_0)).
neg(throwing_something_on_the_floor_target(x1918_0)).
neg(throwing_something_on_the_floor_target(x1923_0)).
neg(throwing_something_on_the_floor_target(x1955_0)).
neg(throwing_something_on_the_floor_target(x1964_0)).
neg(throwing_something_on_the_floor_target(x1965_0)).
pos(throwing_something_on_the_floor_target(x2006_0)).
neg(throwing_something_on_the_floor_target(x2056_0)).
neg(throwing_something_on_the_floor_target(x2092_0)).
neg(throwing_something_on_the_floor_target(x2096_0)).
neg(throwing_something_on_the_floor_target(x2129_0)).
neg(throwing_something_on_the_floor_target(x2175_0)).
pos(throwing_something_on_the_floor_target(x2183_0)).
pos(throwing_something_on_the_floor_target(x2236_0)).
neg(throwing_something_on_the_floor_target(x2241_0)).
neg(throwing_something_on_the_floor_target(x2257_0)).
neg(throwing_something_on_the_floor_target(x2269_0)).
neg(throwing_something_on_the_floor_target(x2283_0)).
neg(throwing_something_on_the_floor_target(x2287_0)).
neg(throwing_something_on_the_floor_target(x2296_0)).
neg(throwing_something_on_the_floor_target(x2337_0)).
neg(throwing_something_on_the_floor_target(x2372_0)).
neg(throwing_something_on_the_floor_target(x2425_0)).
neg(throwing_something_on_the_floor_target(x2434_0)).
neg(throwing_something_on_the_floor_target(x2445_0)).
pos(throwing_something_on_the_floor_target(x2452_0)).
pos(throwing_something_on_the_floor_target(x2454_0)).
pos(throwing_something_on_the_floor_target(x2460_0)).
neg(throwing_something_on_the_floor_target(x2492_0)).
neg(throwing_something_on_the_floor_target(x2503_0)).
neg(throwing_something_on_the_floor_target(x2524_0)).
pos(throwing_something_on_the_floor_target(x2558_0)).
neg(throwing_something_on_the_floor_target(x2581_0)).
pos(throwing_something_on_the_floor_target(x2595_0)).
neg(throwing_something_on_the_floor_target(x2617_0)).
neg(throwing_something_on_the_floor_target(x2657_0)).
neg(throwing_something_on_the_floor_target(x2672_0)).
pos(throwing_something_on_the_floor_target(x2687_0)).
neg(throwing_something_on_the_floor_target(x2688_0)).
neg(throwing_something_on_the_floor_target(x2710_0)).
neg(throwing_something_on_the_floor_target(x2772_0)).
neg(throwing_something_on_the_floor_target(x2784_0)).
neg(throwing_something_on_the_floor_target(x2787_0)).
neg(throwing_something_on_the_floor_target(x2802_0)).
neg(throwing_something_on_the_floor_target(x2814_0)).
neg(throwing_something_on_the_floor_target(x2840_0)).
neg(throwing_something_on_the_floor_target(x2850_0)).
neg(throwing_something_on_the_floor_target(x2864_0)).
neg(throwing_something_on_the_floor_target(x2896_0)).
neg(throwing_something_on_the_floor_target(x2910_0)).
neg(throwing_something_on_the_floor_target(x2987_0)).
neg(throwing_something_on_the_floor_target(x2994_0)).
neg(throwing_something_on_the_floor_target(x3013_0)).
neg(throwing_something_on_the_floor_target(x3039_0)).
neg(throwing_something_on_the_floor_target(x3062_0)).
neg(throwing_something_on_the_floor_target(x3230_0)).
neg(throwing_something_on_the_floor_target(x3283_0)).
neg(throwing_something_on_the_floor_target(x3381_0)).
neg(throwing_something_on_the_floor_target(x3386_0)).
neg(throwing_something_on_the_floor_target(x3494_0)).
pos(throwing_something_on_the_floor_target(x3496_0)).
neg(throwing_something_on_the_floor_target(x3532_0)).
neg(throwing_something_on_the_floor_target(x3600_0)).
neg(throwing_something_on_the_floor_target(x3643_0)).
pos(throwing_something_on_the_floor_target(x3651_0)).
neg(throwing_something_on_the_floor_target(x3664_0)).
neg(throwing_something_on_the_floor_target(x3667_0)).
pos(throwing_something_on_the_floor_target(x3678_0)).
neg(throwing_something_on_the_floor_target(x3722_0)).
neg(throwing_something_on_the_floor_target(x3768_0)).
pos(throwing_something_on_the_floor_target(x3775_0)).
neg(throwing_something_on_the_floor_target(x3807_0)).
neg(throwing_something_on_the_floor_target(x3809_0)).
neg(throwing_something_on_the_floor_target(x3822_0)).
neg(throwing_something_on_the_floor_target(x3828_0)).
pos(throwing_something_on_the_floor_target(x3838_0)).
neg(throwing_something_on_the_floor_target(x3869_0)).
neg(throwing_something_on_the_floor_target(x3883_0)).
pos(throwing_something_on_the_floor_target(x3897_0)).
neg(throwing_something_on_the_floor_target(x3905_0)).
neg(throwing_something_on_the_floor_target(x3933_0)).
neg(throwing_something_on_the_floor_target(x3941_0)).
neg(throwing_something_on_the_floor_target(x3984_0)).
neg(throwing_something_on_the_floor_target(x3987_0)).
neg(throwing_something_on_the_floor_target(x4002_0)).
neg(throwing_something_on_the_floor_target(x4017_0)).
neg(throwing_something_on_the_floor_target(x4065_0)).
neg(throwing_something_on_the_floor_target(x4091_0)).
pos(throwing_something_on_the_floor_target(x4254_0)).
pos(throwing_something_on_the_floor_target(x4326_0)).
neg(throwing_something_on_the_floor_target(x4394_0)).
neg(throwing_something_on_the_floor_target(x4407_0)).
neg(throwing_something_on_the_floor_target(x4417_0)).
neg(throwing_something_on_the_floor_target(x4506_0)).
neg(throwing_something_on_the_floor_target(x4557_0)).
neg(throwing_something_on_the_floor_target(x4592_0)).
neg(throwing_something_on_the_floor_target(x4596_0)).
pos(throwing_something_on_the_floor_target(x4612_0)).
neg(throwing_something_on_the_floor_target(x4649_0)).
neg(throwing_something_on_the_floor_target(x4680_0)).
neg(throwing_something_on_the_floor_target(x4716_0)).
neg(throwing_something_on_the_floor_target(x4732_0)).
neg(throwing_something_on_the_floor_target(x4737_0)).
neg(throwing_something_on_the_floor_target(x4750_0)).
neg(throwing_something_on_the_floor_target(x4752_0)).
neg(throwing_something_on_the_floor_target(x4777_0)).
neg(throwing_something_on_the_floor_target(x4782_0)).
neg(throwing_something_on_the_floor_target(x4814_0)).
neg(throwing_something_on_the_floor_target(x4817_0)).
neg(throwing_something_on_the_floor_target(x4829_0)).
neg(throwing_something_on_the_floor_target(x4872_0)).
neg(throwing_something_on_the_floor_target(x4891_0)).
neg(throwing_something_on_the_floor_target(x4913_0)).
neg(throwing_something_on_the_floor_target(x4921_0)).
neg(throwing_something_on_the_floor_target(x4931_0)).
neg(throwing_something_on_the_floor_target(x4933_0)).
pos(throwing_something_on_the_floor_target(x4938_0)).
neg(throwing_something_on_the_floor_target(x4967_0)).
neg(throwing_something_on_the_floor_target(x4978_0)).
neg(throwing_something_on_the_floor_target(x5047_0)).
neg(throwing_something_on_the_floor_target(x5048_0)).
pos(throwing_something_on_the_floor_target(x5067_0)).
neg(throwing_something_on_the_floor_target(x5077_0)).
pos(throwing_something_on_the_floor_target(x5117_0)).
neg(throwing_something_on_the_floor_target(x5131_0)).
neg(throwing_something_on_the_floor_target(x5147_0)).
neg(throwing_something_on_the_floor_target(x5201_0)).
neg(throwing_something_on_the_floor_target(x5230_0)).
neg(throwing_something_on_the_floor_target(x5240_0)).
neg(throwing_something_on_the_floor_target(x5243_0)).
neg(throwing_something_on_the_floor_target(x5248_0)).
pos(throwing_something_on_the_floor_target(x5287_0)).
neg(throwing_something_on_the_floor_target(x5295_0)).
pos(throwing_something_on_the_floor_target(x5313_0)).
neg(throwing_something_on_the_floor_target(x5334_0)).
neg(throwing_something_on_the_floor_target(x5383_0)).
neg(throwing_something_on_the_floor_target(x5411_0)).
neg(throwing_something_on_the_floor_target(x5437_0)).
neg(throwing_something_on_the_floor_target(x5484_0)).
neg(throwing_something_on_the_floor_target(x5499_0)).
neg(throwing_something_on_the_floor_target(x5501_0)).
pos(throwing_something_on_the_floor_target(x5553_0)).
pos(throwing_something_on_the_floor_target(x5558_0)).
neg(throwing_something_on_the_floor_target(x5562_0)).
pos(throwing_something_on_the_floor_target(x5563_0)).
pos(throwing_something_on_the_floor_target(x5567_0)).
neg(throwing_something_on_the_floor_target(x5581_0)).
neg(throwing_something_on_the_floor_target(x5594_0)).
neg(throwing_something_on_the_floor_target(x5621_0)).
neg(throwing_something_on_the_floor_target(x5636_0)).
neg(throwing_something_on_the_floor_target(x5696_0)).
neg(throwing_something_on_the_floor_target(x5735_0)).
neg(throwing_something_on_the_floor_target(x5825_0)).
pos(throwing_something_on_the_floor_target(x5841_0)).
pos(throwing_something_on_the_floor_target(x5849_0)).
pos(throwing_something_on_the_floor_target(x5854_0)).
neg(throwing_something_on_the_floor_target(x5859_0)).
pos(throwing_something_on_the_floor_target(x5887_0)).
neg(throwing_something_on_the_floor_target(x5923_0)).
neg(throwing_something_on_the_floor_target(x5977_0)).
neg(throwing_something_on_the_floor_target(x5988_0)).
pos(throwing_something_on_the_floor_target(x6006_0)).
neg(throwing_something_on_the_floor_target(x6009_0)).
neg(throwing_something_on_the_floor_target(x6024_0)).
neg(throwing_something_on_the_floor_target(x6058_0)).
pos(throwing_something_on_the_floor_target(x6064_0)).
pos(throwing_something_on_the_floor_target(x6077_0)).
pos(throwing_something_on_the_floor_target(x6100_0)).
neg(throwing_something_on_the_floor_target(x6115_0)).
neg(throwing_something_on_the_floor_target(x6166_0)).
neg(throwing_something_on_the_floor_target(x6186_0)).
neg(throwing_something_on_the_floor_target(x6187_0)).
neg(throwing_something_on_the_floor_target(x6192_0)).
neg(throwing_something_on_the_floor_target(x6205_0)).
pos(throwing_something_on_the_floor_target(x6229_0)).
pos(throwing_something_on_the_floor_target(x6230_0)).
pos(throwing_something_on_the_floor_target(x6297_0)).
neg(throwing_something_on_the_floor_target(x6298_0)).
pos(throwing_something_on_the_floor_target(x6372_0)).
neg(throwing_something_on_the_floor_target(x6379_0)).
neg(throwing_something_on_the_floor_target(x6393_0)).
neg(throwing_something_on_the_floor_target(x6411_0)).
pos(throwing_something_on_the_floor_target(x6491_0)).
neg(throwing_something_on_the_floor_target(x6522_0)).
neg(throwing_something_on_the_floor_target(x6543_0)).
pos(throwing_something_on_the_floor_target(x6573_0)).
neg(throwing_something_on_the_floor_target(x6578_0)).
neg(throwing_something_on_the_floor_target(x6639_0)).
pos(throwing_something_on_the_floor_target(x6659_0)).
neg(throwing_something_on_the_floor_target(x6702_0)).
neg(throwing_something_on_the_floor_target(x6706_0)).
neg(throwing_something_on_the_floor_target(x6758_0)).
neg(throwing_something_on_the_floor_target(x6761_0)).
neg(throwing_something_on_the_floor_target(x6766_0)).
neg(throwing_something_on_the_floor_target(x6791_0)).
neg(throwing_something_on_the_floor_target(x6818_0)).
pos(throwing_something_on_the_floor_target(x6838_0)).
pos(throwing_something_on_the_floor_target(x6844_0)).
neg(throwing_something_on_the_floor_target(x6847_0)).
neg(throwing_something_on_the_floor_target(x6886_0)).
neg(throwing_something_on_the_floor_target(x6899_0)).
neg(throwing_something_on_the_floor_target(x6915_0)).
neg(throwing_something_on_the_floor_target(x6930_0)).
neg(throwing_something_on_the_floor_target(x6931_0)).
neg(throwing_something_on_the_floor_target(x6935_0)).
neg(throwing_something_on_the_floor_target(x6938_0)).
neg(throwing_something_on_the_floor_target(x6939_0)).
neg(throwing_something_on_the_floor_target(x6956_0)).
neg(throwing_something_on_the_floor_target(x6971_0)).
neg(throwing_something_on_the_floor_target(x7093_0)).
neg(throwing_something_on_the_floor_target(x7139_0)).
neg(throwing_something_on_the_floor_target(x7174_0)).
neg(throwing_something_on_the_floor_target(x7185_0)).
neg(throwing_something_on_the_floor_target(x7198_0)).
pos(throwing_something_on_the_floor_target(x7215_0)).
neg(throwing_something_on_the_floor_target(x7257_0)).
neg(throwing_something_on_the_floor_target(x7260_0)).
pos(throwing_something_on_the_floor_target(x7263_0)).
neg(throwing_something_on_the_floor_target(x7288_0)).
neg(throwing_something_on_the_floor_target(x7300_0)).
neg(throwing_something_on_the_floor_target(x7314_0)).
neg(throwing_something_on_the_floor_target(x7323_0)).
neg(throwing_something_on_the_floor_target(x7337_0)).
