%%keep negative probability: 0.0215305815718424
:- style_check(-discontiguous).
neg(throwing_a_pillow_somewhere_target(x17_0)).
pos(throwing_a_pillow_somewhere_target(x210_0)).
pos(throwing_a_pillow_somewhere_target(x224_0)).
neg(throwing_a_pillow_somewhere_target(x232_0)).
pos(throwing_a_pillow_somewhere_target(x243_0)).
neg(throwing_a_pillow_somewhere_target(x292_0)).
neg(throwing_a_pillow_somewhere_target(x295_0)).
pos(throwing_a_pillow_somewhere_target(x299_0)).
neg(throwing_a_pillow_somewhere_target(x422_0)).
neg(throwing_a_pillow_somewhere_target(x510_0)).
neg(throwing_a_pillow_somewhere_target(x518_0)).
neg(throwing_a_pillow_somewhere_target(x550_0)).
neg(throwing_a_pillow_somewhere_target(x623_0)).
neg(throwing_a_pillow_somewhere_target(x648_0)).
neg(throwing_a_pillow_somewhere_target(x656_0)).
pos(throwing_a_pillow_somewhere_target(x803_0)).
neg(throwing_a_pillow_somewhere_target(x906_0)).
pos(throwing_a_pillow_somewhere_target(x913_0)).
neg(throwing_a_pillow_somewhere_target(x914_0)).
pos(throwing_a_pillow_somewhere_target(x924_0)).
neg(throwing_a_pillow_somewhere_target(x945_0)).
neg(throwing_a_pillow_somewhere_target(x950_0)).
neg(throwing_a_pillow_somewhere_target(x1000_0)).
neg(throwing_a_pillow_somewhere_target(x1024_0)).
pos(throwing_a_pillow_somewhere_target(x1100_0)).
neg(throwing_a_pillow_somewhere_target(x1106_0)).
neg(throwing_a_pillow_somewhere_target(x1204_0)).
neg(throwing_a_pillow_somewhere_target(x1234_0)).
pos(throwing_a_pillow_somewhere_target(x1281_0)).
neg(throwing_a_pillow_somewhere_target(x1305_0)).
pos(throwing_a_pillow_somewhere_target(x1311_0)).
pos(throwing_a_pillow_somewhere_target(x1387_0)).
pos(throwing_a_pillow_somewhere_target(x1392_0)).
neg(throwing_a_pillow_somewhere_target(x1450_0)).
pos(throwing_a_pillow_somewhere_target(x1496_0)).
neg(throwing_a_pillow_somewhere_target(x1555_0)).
neg(throwing_a_pillow_somewhere_target(x1569_0)).
pos(throwing_a_pillow_somewhere_target(x1602_0)).
neg(throwing_a_pillow_somewhere_target(x1631_0)).
neg(throwing_a_pillow_somewhere_target(x1646_0)).
neg(throwing_a_pillow_somewhere_target(x1649_0)).
pos(throwing_a_pillow_somewhere_target(x1667_0)).
neg(throwing_a_pillow_somewhere_target(x1715_0)).
neg(throwing_a_pillow_somewhere_target(x1717_0)).
neg(throwing_a_pillow_somewhere_target(x1751_0)).
neg(throwing_a_pillow_somewhere_target(x1757_0)).
neg(throwing_a_pillow_somewhere_target(x1769_0)).
neg(throwing_a_pillow_somewhere_target(x1771_0)).
neg(throwing_a_pillow_somewhere_target(x1773_0)).
neg(throwing_a_pillow_somewhere_target(x1835_0)).
pos(throwing_a_pillow_somewhere_target(x1855_0)).
neg(throwing_a_pillow_somewhere_target(x1881_0)).
neg(throwing_a_pillow_somewhere_target(x1900_0)).
pos(throwing_a_pillow_somewhere_target(x2098_0)).
pos(throwing_a_pillow_somewhere_target(x2137_0)).
neg(throwing_a_pillow_somewhere_target(x2278_0)).
neg(throwing_a_pillow_somewhere_target(x2310_0)).
neg(throwing_a_pillow_somewhere_target(x2409_0)).
neg(throwing_a_pillow_somewhere_target(x2619_0)).
neg(throwing_a_pillow_somewhere_target(x2631_0)).
neg(throwing_a_pillow_somewhere_target(x2711_0)).
neg(throwing_a_pillow_somewhere_target(x2777_0)).
neg(throwing_a_pillow_somewhere_target(x2825_0)).
neg(throwing_a_pillow_somewhere_target(x2856_0)).
neg(throwing_a_pillow_somewhere_target(x2871_0)).
neg(throwing_a_pillow_somewhere_target(x2873_0)).
neg(throwing_a_pillow_somewhere_target(x2894_0)).
neg(throwing_a_pillow_somewhere_target(x2913_0)).
neg(throwing_a_pillow_somewhere_target(x2915_0)).
neg(throwing_a_pillow_somewhere_target(x2920_0)).
neg(throwing_a_pillow_somewhere_target(x2948_0)).
neg(throwing_a_pillow_somewhere_target(x2964_0)).
neg(throwing_a_pillow_somewhere_target(x2986_0)).
neg(throwing_a_pillow_somewhere_target(x3028_0)).
neg(throwing_a_pillow_somewhere_target(x3033_0)).
neg(throwing_a_pillow_somewhere_target(x3143_0)).
neg(throwing_a_pillow_somewhere_target(x3147_0)).
neg(throwing_a_pillow_somewhere_target(x3153_0)).
neg(throwing_a_pillow_somewhere_target(x3181_0)).
neg(throwing_a_pillow_somewhere_target(x3192_0)).
neg(throwing_a_pillow_somewhere_target(x3202_0)).
neg(throwing_a_pillow_somewhere_target(x3322_0)).
neg(throwing_a_pillow_somewhere_target(x3409_0)).
neg(throwing_a_pillow_somewhere_target(x3411_0)).
neg(throwing_a_pillow_somewhere_target(x3422_0)).
neg(throwing_a_pillow_somewhere_target(x3501_0)).
neg(throwing_a_pillow_somewhere_target(x3574_0)).
pos(throwing_a_pillow_somewhere_target(x3598_0)).
neg(throwing_a_pillow_somewhere_target(x3602_0)).
neg(throwing_a_pillow_somewhere_target(x3636_0)).
pos(throwing_a_pillow_somewhere_target(x3651_0)).
pos(throwing_a_pillow_somewhere_target(x3663_0)).
neg(throwing_a_pillow_somewhere_target(x3708_0)).
neg(throwing_a_pillow_somewhere_target(x3710_0)).
neg(throwing_a_pillow_somewhere_target(x3764_0)).
neg(throwing_a_pillow_somewhere_target(x3768_0)).
neg(throwing_a_pillow_somewhere_target(x3770_0)).
pos(throwing_a_pillow_somewhere_target(x3794_0)).
neg(throwing_a_pillow_somewhere_target(x3803_0)).
neg(throwing_a_pillow_somewhere_target(x3850_0)).
neg(throwing_a_pillow_somewhere_target(x3865_0)).
neg(throwing_a_pillow_somewhere_target(x3871_0)).
pos(throwing_a_pillow_somewhere_target(x3942_0)).
neg(throwing_a_pillow_somewhere_target(x3966_0)).
pos(throwing_a_pillow_somewhere_target(x3986_0)).
neg(throwing_a_pillow_somewhere_target(x3989_0)).
neg(throwing_a_pillow_somewhere_target(x3996_0)).
neg(throwing_a_pillow_somewhere_target(x4194_0)).
neg(throwing_a_pillow_somewhere_target(x4199_0)).
pos(throwing_a_pillow_somewhere_target(x4215_0)).
neg(throwing_a_pillow_somewhere_target(x4253_0)).
neg(throwing_a_pillow_somewhere_target(x4472_0)).
neg(throwing_a_pillow_somewhere_target(x4473_0)).
neg(throwing_a_pillow_somewhere_target(x4476_0)).
pos(throwing_a_pillow_somewhere_target(x4521_0)).
neg(throwing_a_pillow_somewhere_target(x4551_0)).
neg(throwing_a_pillow_somewhere_target(x4613_0)).
pos(throwing_a_pillow_somewhere_target(x4621_0)).
neg(throwing_a_pillow_somewhere_target(x4638_0)).
pos(throwing_a_pillow_somewhere_target(x4709_0)).
pos(throwing_a_pillow_somewhere_target(x4726_0)).
neg(throwing_a_pillow_somewhere_target(x4766_0)).
neg(throwing_a_pillow_somewhere_target(x4891_0)).
neg(throwing_a_pillow_somewhere_target(x4895_0)).
neg(throwing_a_pillow_somewhere_target(x4915_0)).
neg(throwing_a_pillow_somewhere_target(x4930_0)).
neg(throwing_a_pillow_somewhere_target(x4995_0)).
pos(throwing_a_pillow_somewhere_target(x5038_0)).
neg(throwing_a_pillow_somewhere_target(x5121_0)).
pos(throwing_a_pillow_somewhere_target(x5161_0)).
neg(throwing_a_pillow_somewhere_target(x5335_0)).
neg(throwing_a_pillow_somewhere_target(x5380_0)).
neg(throwing_a_pillow_somewhere_target(x5420_0)).
pos(throwing_a_pillow_somewhere_target(x5441_0)).
neg(throwing_a_pillow_somewhere_target(x5585_0)).
neg(throwing_a_pillow_somewhere_target(x5603_0)).
neg(throwing_a_pillow_somewhere_target(x5637_0)).
neg(throwing_a_pillow_somewhere_target(x5682_0)).
neg(throwing_a_pillow_somewhere_target(x5793_0)).
neg(throwing_a_pillow_somewhere_target(x5814_0)).
neg(throwing_a_pillow_somewhere_target(x5866_0)).
neg(throwing_a_pillow_somewhere_target(x5918_0)).
neg(throwing_a_pillow_somewhere_target(x5973_0)).
neg(throwing_a_pillow_somewhere_target(x6003_0)).
neg(throwing_a_pillow_somewhere_target(x6103_0)).
neg(throwing_a_pillow_somewhere_target(x6117_0)).
neg(throwing_a_pillow_somewhere_target(x6157_0)).
neg(throwing_a_pillow_somewhere_target(x6164_0)).
neg(throwing_a_pillow_somewhere_target(x6240_0)).
neg(throwing_a_pillow_somewhere_target(x6260_0)).
neg(throwing_a_pillow_somewhere_target(x6290_0)).
pos(throwing_a_pillow_somewhere_target(x6377_0)).
pos(throwing_a_pillow_somewhere_target(x6489_0)).
neg(throwing_a_pillow_somewhere_target(x6537_0)).
neg(throwing_a_pillow_somewhere_target(x6614_0)).
neg(throwing_a_pillow_somewhere_target(x6637_0)).
neg(throwing_a_pillow_somewhere_target(x6638_0)).
neg(throwing_a_pillow_somewhere_target(x6653_0)).
pos(throwing_a_pillow_somewhere_target(x6700_0)).
pos(throwing_a_pillow_somewhere_target(x6711_0)).
pos(throwing_a_pillow_somewhere_target(x6766_0)).
neg(throwing_a_pillow_somewhere_target(x6797_0)).
pos(throwing_a_pillow_somewhere_target(x6834_0)).
pos(throwing_a_pillow_somewhere_target(x6850_0)).
neg(throwing_a_pillow_somewhere_target(x6882_0)).
pos(throwing_a_pillow_somewhere_target(x6893_0)).
neg(throwing_a_pillow_somewhere_target(x6908_0)).
neg(throwing_a_pillow_somewhere_target(x6963_0)).
neg(throwing_a_pillow_somewhere_target(x6967_0)).
neg(throwing_a_pillow_somewhere_target(x7033_0)).
neg(throwing_a_pillow_somewhere_target(x7085_0)).
neg(throwing_a_pillow_somewhere_target(x7152_0)).
neg(throwing_a_pillow_somewhere_target(x7168_0)).
neg(throwing_a_pillow_somewhere_target(x7290_0)).
neg(throwing_a_pillow_somewhere_target(x7309_0)).
neg(throwing_a_pillow_somewhere_target(x7325_0)).
