lr: 1e-3
model_params: !!python/tuple
- !!python/tuple
  - 36
  - 32
  - 32
  - 26
- 32
- 30
model_type: joint
weight: !!python/object/apply:torch._utils._rebuild_tensor_v2
- !!python/object/apply:torch.storage._load_from_bytes
  - !!binary |
    gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
    AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
    aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
    Z2UKcQFYDwAAADEwNzk0OTgxOTk2NTkzNnECWAMAAABjcHVxA0seTnRxBFEugAJdcQBYDwAAADEw
    Nzk0OTgxOTk2NTkzNnEBYS4eAAAAAAAAAGRa7T8eyA0/GiWuQJyba0AQooY/voReP8sDMkBEREhB
    /O47P5FwqkBVVXpCGBPgPiENmkAyB8E/JsaHQBPvIT5gaARAL67DPpFwKkAVjtQ+ZFptP5yb60DW
    AzQ/uxFQPxolLkGdNiBAIQ2aP/FN/D/LAzI/ywMyQA==
- 0
- !!python/tuple
  - 30
- !!python/tuple
  - 1
- false
- !!python/object/apply:collections.OrderedDict
  - []
